### ISSUE TITLE
«Hide Inbox Footer» isn't working as expected

### ISSUE THREAD

**Issue by yermulnik** [zoidsh/meru#439]
Moved from #437 

The `Hide Inbox Footer` item (when enabled) in `View`→`Gmail Appearance` menu doesn't hide the block it is expected to hide:
![Image](https://github.com/user-attachments/assets/3f20d198-89e7-4091-950f-e43b9783be1f)

[main/packages/app/gmail/gmail.css#L10-L16](https://github.com/zoidsh/meru/blob/main/packages/app/gmail/gmail.css?rgh-link-date=2025-05-19T16%3A51%3A24.000Z#L10-L16) — the role and related href seem to belong in different level of divs for me here

```css
/* Gmail Inbox Footer */
html.meru.hide-inbox-footer
	[role="contentinfo"]:has(
		a[href="https://www.google.com/gmail/about/policy/"]
	) {
	display: none !important;
}
```

![Image](https://github.com/user-attachments/assets/c2d599f1-512f-4e9a-8307-b8893c9ae01b)
